baseurl: https://marcin.cylke.com.pl/
disablePathToLower: true
languageCode: en-us
title: Tech ramblings by Marcin
name: Tech ramblings by Marcin
theme: simple-style
# theme: hugo-prose
newContentEditor: vim
author: Marcin Cylke
buildDrafts: true
paginate: 20
favicon: true
services:
  rss:
    limit: 10
params:
    disqus: marcinbloguje
    LatestCount: 10
    utterances:
      repo: zygm0nt/hugo-blog-incarnation
      endpoint: "https://utteranc.es/"
menu:
  main:
  - identifier: about
    name: about me 
    pre: <i class='fa fa-heart'></i>
    url: /about/
    weight: -110
    #  - identifier: map-my-dreams
   #name: map-my-dreams
    #pre: <i class='fa fa-heart'></i>
    #url: /map-my-dreams/
    #weight: -110
    #- identifier: spotify-cover-viewer
    #name: spotify-cover-viewer
    #pre: <i class='fa fa-heart'></i>
    #url: /spotify-cover-viewer/
    #weight: -110
   
taxonomies:
    tag: "tags"
    category: "categories"

module:
  imports:
  - path: github.com/hugomods/icons/vendors/bootstrap
  - path: github.com/hugomods/images
  - path: github.com/hugomods/bootstrap
  - path: github.com/hugomods/katex
  - path: github.com/hugomods/utterances

