baseurl: https://marcin.cylke.com.pl/
disablePathToLower: true
languageCode: en-us
title: Tech ramblings by Marcin
theme: PaperMod
newContentEditor: vim
author: Marcin Cylke
buildDrafts: true
pagination:
  pagerSize: 20

services:
  rss:
    limit: 10

params:
  env: production
  title: Tech ramblings by Marcin
  description: "Tech ramblings by Marcin - software engineering, distributed systems, and more"
  author: Marcin Cylke

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true

  comments: true

  homeInfoParams:
    Title: "Tech ramblings by Marcin"
    Content: "Software engineering, distributed systems, and trivia."

  socialIcons:
    - name: github
      url: "https://github.com/zygm0nt"
    - name: rss
      url: "/index.xml"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    guessSyntax: true
    tabWidth: 4

taxonomies:
  tag: "tags"
  category: "categories"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40
    - identifier: travels
      name: Travels
      url: /travels/
      weight: 50
