baseurl: http://marcin.cylke.com.pl/
disablePathToLower: true
languageCode: en-us
title: Tech ramblings by Marcin
name: Tech ramblings by Marcin
theme: natrium
newContentEditor: vim
googleAnalytics: "UA-172194-10"
author: Marcin Cylke
buildDrafts: true
params:
    disqus: marcinbloguje
menu:
  main:
  - identifier: about
    name: about me 
    pre: <i class='fa fa-heart'></i>
    url: /about/
    weight: -110
    
taxonomies:
    tag: "tags"
    category: "categories"
